config/routes.rb
Soobooki::Application.routes.draw do
  Mercury::Engine.routes
  mount Ckeditor::Engine => '/ckeditor'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "email_confirmation/:id" =>"users#email_confirmation", :as => "email_confirmation"
  get "need_confirmation" =>"users#need_confirmation", :as => "need_confirmation"
  get "send_confirmation" =>"users#send_confirmation", :as => "send_confirmation"

  get "edit_search_target/:id" => "users#edit_search_target", :as => "edit_search_target"

  get "bookshelf/:id" => "book_posts#index", :as => "bookshelf"
  get "edit_bookshelf_privacy/:id" => "users#edit_bookshelf_privacy", :as => "edit_bookshelf_privacy"
  get "edit_book_post_privacy/:id" => "book_posts#edit_privacy", :as => "edit_book_post_privacy"
  get "edit_book_api/:id" => "users#edit_book_api", :as => "edit_book_api"

  get "movieshelf/:id" => "movie_posts#index", :as => "movieshelf"
  get "edit_movieshelf_privacy/:id" => "users#edit_movieshelf_privacy", :as => "edit_movieshelf_privacy"
  get "edit_movie_post_privacy/:id" => "movie_posts#edit_privacy", :as => "edit_movie_post_privacy"
  get "edit_movie_api/:id" => "users#edit_movie_api", :as => "edit_movie_api"

  get "user_image_crop/:id" => "users#crop_image", :as => "user_image_crop"
  get "fb_profile_pictures/:id" => "users#fb_profile_pictures", :as => "fb_profile_pictures"

  put "friendships/:id" => "friendships#approve"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  match '/auth/save_access_token' => 'authentications#save_access_token'

  resources :users
  resources :books do
    collection { get :search }
  end
  resources :book_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :movies do
    collection { get :search }
  end
  resources :movie_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :sessions
  resources :password_resets
  resources :friendships
  resources :authentications
  resources :comments
  resources :notifications

  root :to => 'sessions#new'

end

app/models/book_post.rb
class BookPost < ActiveRecord::Base
  attr_accessible :book_id, :review, :user_id, :user, :year,:month,:day,
                  :title, :image, :remote_image_url

  belongs_to :book
  belongs_to :user

  has_many :comments, order: 'created_at', dependent: :destroy
  has_many :notifications, dependent: :destroy

  mount_uploader :image, ImageUploader

  def title
    if super.present?
      return super
    else
      return book.title unless book.nil?
    end
  end

  def image_url(*args)
    if super.present?
      return super
    else
      return book.image_url(*args) unless book.nil?
    end
  end
end

app/controllers/book_posts_controller.rb
class BookPostsController < ApplicationController
  # GET /book_posts
  # GET /book_posts.json
  def index
    if params.has_key?(:id)
      @user = find_user(params[:id])
      redirect_to log_in_path,
      notice: "Couldn't find the user with id: "+params[:id] and return if @user.nil?
    else
      @user = logged_in? # sets @user to current_user
      return if @user.nil?
    end
    if itemshelf_privacy_valid?
      posts_index
    end
  end

  # GET /book_posts/1
  # GET /book_posts/1.json
  def show
    @book_post = BookPost.find(params[:id])
    @user = @book_post.user
    @book = Book.find(@book_post.book_id)
    @controller = params[:controller]
    @action = params[:action]

    if post_privacy_valid?
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @book_post }
      end
    end
  end

  # GET /book_posts/new
  # GET /book_posts/new.json
  def new
    @book_post = BookPost.new(year: Time.now.year, month: Time.now.month, day:Time.now.day)
    @controller = params[:controller]

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    #TODO: check if the book already exists.

    if params[:api].present?
      create_from_search and return
    end
    @book = Book.new(title: params[:book_post][:title], image: params[:book_post][:image],
                 remote_image_url: params[:book_post][:remote_image_url])
    @book_post = @book.book_posts.build(params[:book_post])
    @book_post.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book_post, notice: 'Book post was successfully created.' }
      else
        flash[:notice] = @book.errors.full_messages[0]
        format.html { render action: "new" }
      end
    end
  end

  def create_from_search
    if params[:api] == "daum"
      params.map do |key,value|
        params[key] = value.gsub('<b>','').gsub('</b>','') unless value.nil?
      end
      image_url = "http://book.daum-img.net/image/"+params[:api_id]
      unless remote_image_exists?(image_url)
        image_url = "http://book.daum-img.net/image/KOR"+params[:isbn13]
        image_url = nil if not remote_image_exists?(image_url)
      end
    elsif params[:api] == "amazon"
      image_url = params[:cover_image_url]
    end

    @book = Book.new(title: params[:title], remote_image_url: image_url, authors: params[:authors],
                 translators: params[:translators], publisher: params[:publisher], category: params[:category],
                 pub_date: params[:pub_date], api_id: params[:api_id], isbn: params[:isbn], isbn13: params[:isbn13])
    @book.book_posts.build(user_id: current_user.id, year: Time.now.year, month: Time.now.month,
                     day: Time.now.day)
    @api_id = params[:api_id]
    respond_to do |format|
      if @book.save!
        format.js
      end
    end
  end

  # GET /book_posts/1/edit
  def edit
    @book_post = current_user.book_posts.find(params[:id])
    @book = Book.find(@book_post.book_id)
    @controller = params[:controller]
  end

  # PUT /book_posts/1
  # PUT /book_posts/1.json
  def update
    @book_post = current_user.book_posts.find(params[:id])
    review = params[:book_post][:review]
    params[:book_post][:review] = Sanitize.clean(review,Sanitize::Config::RELAXED)

    respond_to do |format|
      if @book_post.update_attributes(params[:book_post])
        format.html { redirect_to @book_post, notice: 'Book post was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /book_posts/1
  # DELETE /book_posts/1.json
  def destroy
    @book_post = current_user.book_posts.find(params[:id])
    @book_post.destroy

    respond_to do |format|
      format.html { redirect_to book_posts_url, notice: 'Book post was successfully deleted.'}
      format.json { head :no_content }
    end
  end

  def mercury_update
    book_post = current_user.book_posts.find(params[:id])
    book_post.review = Sanitize.clean(params[:content][:book_post_review][:value],
                                Sanitize::Config::RELAXED)
    book_post.save!
    render text: ""
  end

  def edit_privacy
    @book_post = BookPost.find(params[:id])
    @book_post.privacy = params[:privacy]
    @book_post.save
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/book_posts_helper.rb
module BookPostsHelper
  def find_book(id)
    @book = Book.find_by_id(id)
  end
end

app/views/book_posts/_user.html.erb
<ul class="thumbnails">
  <li class="profile-pic">
    <% if @user.image_url.blank?%>
      <% if @user == current_user %>
        <%= link_to image_tag("http://placehold.it/130x130"),\
            edit_user_path(@user.id), :class => "thumbnail" %>
      <% else %>
        <%= image_tag "http://placehold.it/130x130", class: "thumbnail" %>
      <% end %>
    <% else %>
      <% if @user == current_user %>
        <%= link_to image_tag(@user.image_url(:thumb).to_s+
                          "?#{File.mtime(@user.image.file.path).to_i.to_s}"),
                          edit_user_path(@user.id), :class => "thumbnail" %>
      <% else %>
        <%= image_tag @user.image_url(:thumb).to_s, class: "thumbnail" %>
      <% end %>
    <% end %>
  </li>
</ul>
<% if @user.first_name? %>
  <h4> Name: </h4>
  <p>
    <%= @user.first_name+" "+@user.last_name %>
  </p>
<% else %>
  <h4> User email: </h4>
  <p>
    <%= @user.email %>
  </p>
<% end %>
<% if @user.bookshelf_name? %>
  <h4> Bookshelf ID: </h4>
  <p>
    <%= @user.bookshelf_name %>
  </p>
<% end %>
<% if @user.info? %>
  <h4> Info: </h4>
  <p>
    <%= simple_format @user.info %>
  </p>
<% end %>
<% if @user.admin %>
  <%= link_to "Users Admin Page", users_path, class: "btn" %>
<% end %>

app/views/book_posts/create.js.erb
$('.add_<%= @api_id %>').hide()
//$('.search-results').hide()
//$('.bookshelf-container').show();

app/views/book_posts/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Edit Book</h1>
    <%= render 'items/form', post: @book_post %>
  </div>
</div>

app/views/book_posts/edit_privacy.js.erb
book_post.privacy = <%= @book_post.privacy %>

app/views/book_posts/index.html.erb
<div class="row">
  <div class="search-results span7 offset2"></div>
  <div class="bookshelf-container span7 offset2">
    <% if @posts_size == 0 %>
      <% if current_user == @user %>
        <div class="usage-info">
          <h2>Usage Guide</h2>
          <h3>1. Search for a book</h3>
          <%= image_tag "book-search-bar.png" %> 
          (click the book icon for book search)
          <h3>2. Add it to your bookshelf</h3>
          <%= image_tag "book.png" %>
          <h3>3. Write reviews and share them with others</h3>
          <%= image_tag "bookshelf.png" %>
        </div>
      <% else %>
        <h3><%= user_name(@user)%> has not added any books yet. </h3>
      <% end %>
    <% else %>
      <div class="bookshelf">
        <%= render "items/itemshelf"%>
      </div>
      <% unless @next_index >= @posts_size %>
        <%= link_to "See More", bookshelf_path(id: @user.id, next_index: @next_index),
            class: "btn see-more", remote: true %>
      <% end %>
    <% end %>
  </div>
  <div class="span3">
    <%= render 'users/user' %>
  </div>
</div>

app/views/book_posts/index.js.erb
<% if @last_month_posts %>
   <% @last_month_posts.each do |post| %>
     <% item = find_book(post.book_id) %>
     <% if item %>
       $(".bookshelf ul.<%=post.year%>_<%=post.month%>").append("<%= j render "items/item_thumbnail", :item => item, :post => post %>")
     <% end %>
   <% end %>
<% end %>
$(".bookshelf").append("<%= j render "items/itemshelf" %>")
$("a.see-more").attr("href", "<%= j bookshelf_path(id: @user.id, next_index: @next_index) %>")
<% if @next_index >= @posts_size %>
   $("a.see-more").hide()
<% end %>

app/views/book_posts/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Add Book</h1>
    <%= render 'items/form', post: @book_post %>
  </div>
</div>

app/views/book_posts/show.html.erb
<%= javascript_include_tag "mercury_override" %>
<div class="row">
  <div class="search-results span6 offset2"></div>
  <div class="book-post-container span6 offset2">
    <h1><%= @book_post.title %></h1>
    <% if @book_post.image_url.present? %>
      <%= image_tag @book_post.image_url(:default).to_s %>        
    <% end %>
    <% if @book_post.year != 0 %>
      <h4> Date Read </h4>
      <%= format_date(@book_post.year,@book_post.month,@book_post.day) %>
    <% end %>
    <p>
      <div id="book_post_review" class="mercury-region" data-type="editable">
        <%= raw @book_post.review %>
      </div>
    </p>
    <%= render "comments/comment_list", post: @book_post %>
    <% if current_user.present? %>
      <%= render "comments/new_comment", post: @book_post %>
    <% end %>
    <% if current_user == @user %>
      <%= link_to 'Edit Post', edit_book_post_path(@book_post), :class => "btn", id: "ck_edit_link" %>
      <%= link_to 'Mercury Editor', "/editor"+request.path, class: "btn", id: "mercury_edit_link", data: {save_url: mercury_update_book_post_path(@book_post)} %>
      <%= link_to 'Delete', book_post_path(@book_post), 
          :confirm => "Are you sure you want to delete '#{@book.title}'?",
          :method => :delete, :class => "btn", id: "delete_link"%>
    <% end %>
  </div>
  <div class="span3 offset1">
    <%= render 'users/user' %>
  </div>
</div>