config/routes.rb
Soobooki::Application.routes.draw do
  Mercury::Engine.routes
  mount Ckeditor::Engine => '/ckeditor'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "email_confirmation/:id" =>"users#email_confirmation", :as => "email_confirmation"
  get "need_confirmation" =>"users#need_confirmation", :as => "need_confirmation"
  get "send_confirmation" =>"users#send_confirmation", :as => "send_confirmation"

  get "edit_search_target/:id" => "users#edit_search_target", :as => "edit_search_target"

  get "bookshelf/:id" => "book_posts#index", :as => "bookshelf"
  get "edit_bookshelf_privacy/:id" => "users#edit_bookshelf_privacy", :as => "edit_bookshelf_privacy"
  get "edit_book_post_privacy/:id" => "book_posts#edit_privacy", :as => "edit_book_post_privacy"
  get "edit_book_api/:id" => "users#edit_book_api", :as => "edit_book_api"

  get "movieshelf/:id" => "movie_posts#index", :as => "movieshelf"
  get "edit_movieshelf_privacy/:id" => "users#edit_movieshelf_privacy", :as => "edit_movieshelf_privacy"
  get "edit_movie_post_privacy/:id" => "movie_posts#edit_privacy", :as => "edit_movie_post_privacy"
  get "edit_movie_api/:id" => "users#edit_movie_api", :as => "edit_movie_api"

  get "user_image_crop/:id" => "users#crop_image", :as => "user_image_crop"
  get "fb_profile_pictures/:id" => "users#fb_profile_pictures", :as => "fb_profile_pictures"

  put "friendships/:id" => "friendships#approve"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  match '/auth/save_access_token' => 'authentications#save_access_token'

  resources :users
  resources :books do
    collection { get :search }
  end
  resources :book_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :movies do
    collection { get :search }
  end
  resources :movie_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :sessions
  resources :password_resets
  resources :friendships
  resources :authentications
  resources :comments
  resources :notifications

  root :to => 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation, :image, :remote_image_url,\
                  :info, :soobooki_id, :first_name, :last_name, :crop_x, :crop_y, :crop_w, :crop_h

  validates :email, :presence => :true,
                    :uniqueness => {:case_sensitive => false},
                    :length => {:minimun => 3, :maximum => 254},
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  validates_length_of :password, :minimun => 1, :maximum => 254
  validates :soobooki_id, :uniqueness => {:case_sensitive => false},
                       :length => {:minimun => 1, :maximum => 254},
                       :format => {:with => /^[a-z]+[a-z0-9\_\-]+$/i},
                       :allow_blank => true

  before_validation :no_password_omniauth

  has_many :authentications, :dependent => :destroy

  has_many :book_posts, :dependent => :destroy
  has_many :books, :through => :book_posts

  has_many :movie_posts, :dependent => :destroy
  has_many :movies, :through => :movie_posts

  has_many :comments, :dependent => :destroy

  has_many :notifications, :foreign_key => "receiver_id", :dependent => :destroy
  has_many :inverse_notifications, :class_name => "Notification",:foreign_key => "sender_id",
           :dependent => :destroy

  has_many :direct_friendships, :class_name => "Friendship", :dependent => :destroy,
           :conditions => "approved = true"
  has_many :direct_friends, :through => :direct_friendships, :source => :friend
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id",
           :dependent => :destroy, :conditions => "approved = true"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :pending_friendships, :class_name => "Friendship",
           :conditions => "approved = false"
  has_many :pending_friends, :through => :pending_friendships, :source => :friend
  has_many :requested_friendships, :class_name => "Friendship",
           :conditions => "approved = false", :foreign_key => "friend_id"
  has_many :requested_friends, :through => :requested_friendships, :source => :user

  mount_uploader :image, ProfilePicUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_image

  def friends
    direct_friends | inverse_friends
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def send_email_confirmation
    generate_token(:email_confirmation_token)
    save!
    UserMailer.email_confirmation(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  #the following two methods are a dirty hack to bypass the validate_presense_of :password
  #validtaion automatically genearated by "has_secure_password"
  def no_password_omniauth
    self.password_digest = 0 unless password_required
  end

  def password_required
    (authentications.empty? || !password_digest.blank?)
  end

  def only_omniauth?
    authentications.size == 1 and
      (password_digest.blank? or password_digest == 0)
  end

  def crop_image
    image.recreate_versions! if crop_x.present?
  end

  def get_fb_profile_pictures(uid)
    fb_auth = self.authentications.find_by_provider_and_uid('Facebook', uid)
    profile_pictures = []
    if fb_auth.present?
      url = URI::HTTPS.build(:host  => 'graph.facebook.com',
                       :path  => '/'+fb_auth.uid,
                       :query => 'access_token='+fb_auth.access_token+'&fields=albums')
      response = HTTParty.get(url.to_s)
      response['albums']['data'].each do |album|
        if album['name'] == "Profile Pictures"
          url = URI::HTTPS.build(:host  => 'graph.facebook.com',
                           :path  => '/'+album['id']+'/photos',
                           :query => 'access_token='+fb_auth.access_token)
          response = HTTParty.get(url.to_s)
          response['data'].each do |picture|
            profile_pictures << {thumbnail: picture['picture'], large: picture['source']}
          end
          return profile_pictures
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :logged_in?, except: [:new,:create,
                               :email_confirmation,:need_confirmation,:send_confirmation]
  def index
    if current_user
      raise AcessDenied unless current_user.admin?
      @users = User.find(:all, order: "created_at DESC")

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
      end
    else
      redirect_to log_in_path
    end
  end

  def show
    @user = User.find(params[:id])
    @book_posts = @user.book_posts.order("year DESC","month DESC","day DESC","created_at DESC")
    @movie_posts = @user.movie_posts.order("year DESC","month DESC","day DESC","created_at DESC")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @user.send_email_confirmation
      redirect_to root_url, :notice => "A confirmation link was sent to your email.
                          Please click on the link to finish sign up!"
    else
      flash[:notice] = @user.errors.full_messages[0]
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id
  end

  def update
    #    return render text: "#{params}"
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id

    @user.attributes = params[:user]
    respond_to do |format|
      if @user.save
        format.html {
          @current_user = nil
          if params[:user][:image].present? or params[:user][:remote_image_url].present?
            redirect_to user_image_crop_path(@user)
          else
            redirect_to bookshelf(current_user),
            notice: 'User was successfully updated.'
          end
        }
        format.json { head :no_content }
      else
        flash[:notice] = @user.errors.full_messages[0]
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def crop_image
    @user = User.find(params[:id])
  end

  def fb_profile_pictures
    @user = User.find(params[:id])
    fb_auth = @user.authentications.find_by_provider('Facebook')
    if fb_auth.present?
      @profile_pictures = @user.get_fb_profile_pictures
    else
      flash[:notice] = "User account not connected to Facebook yet. Please add Facebook authentication."
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id || current_user.admin?
    @user.destroy

    respond_to do |format|
      format.html {
        unless current_user.admin?
          session[:user_id] = nil
          redirect_to root_url, :notice => "User account deleted."
        else
          redirect_to users_path, :notice => "User account deleted."
        end
      }
      format.json { head :no_content }
    end
  end

  def email_confirmation
    @user = User.find_by_email_confirmation_token(params[:id])
    if @user
      @user.email_confirmed = true
      @user.save!
      session[:user_id] = @user.id
      redirect_to bookshelf(current_user), :alert => "Email has been confirmed. Sign up complete!"
    else
      redirect_to root_url, :alert => "Email confirmation token was incorrect.
                                       Please try again."
    end
  end

  def need_confirmation
  end

  def send_confirmation
    if session[:user_email]
      user = User.find_by_email(session[:user_email])
      user.send_email_confirmation
      redirect_to root_url, :notice => "Confirmation email has been sent!"
    else
      redirect_to root_url, :notice => "Email information not found.
                      Try logging in or signing up."
    end
  end

  def edit_bookshelf_privacy
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id
    @user.bookshelf_privacy = params[:privacy]
    respond_to do |format|
      if @user.save
        format.js
      end
    end
  end

  def edit_movieshelf_privacy
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id
    @user.movieshelf_privacy = params[:privacy]
    respond_to do |format|
      if @user.save
        format.js
      end
    end
  end

  def edit_book_api
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id
    @user.book_api = params[:book_api]
    respond_to do |format|
      if @user.save
        format.js
      end
    end
  end

  def edit_movie_api
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id
    @user.movie_api = params[:movie_api]
    respond_to do |format|
      if @user.save
        format.js
      end
    end
  end

  def edit_search_target
    @user = User.find(params[:id])
    raise AccessDenied unless current_user.id == @user.id
    @user.search_target = params[:search_target]
    respond_to do |format|
      if @user.save
        format.js
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_edit.html.erb
<%= form_for(@user, html: {multipart: true}) do |f| %>
  <div class="profile-pic">
    <% unless @user.image_url.blank? %>
      <% filename = @user.image.file.filename %>
      <% if FileTest.exists?(@user.image.file.path.gsub(filename,'medium_'+filename)) %>
        <%= image_tag(@user.image_url(:medium).to_s+
                  "?#{File.mtime(@user.image.file.path).to_i.to_s}") %>
      <% else %>
        <%= image_tag(@user.image_url(:thumb).to_s) %>
      <% end %>
    <% else %>
      <%= image_tag("http://placehold.it/250x250") %>
    <% end %>
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "span2" %>
    </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "span2" %>
    </div>
    <div class="field">
      <%= f.label :soobooki_id, "Soobooki ID" %>
      <%= f.text_field :soobooki_id %></br>
      Your bookshelf's URL will be: soobooki.com/bookshelf/#soobooki_id</br>
    </div>
  </div>
  <div class="profile-pic-actions">
    <% unless @user.image_url.blank? %>
      <%= link_to "Crop Again", user_image_crop_path(@user), class: "btn" %>
    <% end %>
    <% fb_auth = @user.authentications.find_by_provider("Facebook") %>
    <% if fb_auth %>
      <%= link_to "Choose picture from Facebook", fb_profile_pictures_path(@user), class: "btn" %>
    <% end %>
  </div>
  <div class="image-fields">
    <div class="image field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <div class="remote-image field">
      <%= f.label :remote_image_url, "or image URL" %>
      <%= f.text_field :remote_image_url %>
    </div>
  </div>
  <div class="field">
    <%= f.label :info %>
    <%= f.text_area :info, rows:10, class:"span6" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn" %>
  </div>
<% end %>

app/views/users/_form_new.html.erb
<%= form_for(@user, html: {multipart: true}) do |f| %>
  <div class="names">
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class:"span" %>
    </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class:"span2" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class:"span3" %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class:"span3"%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"span3"%>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<ul class="thumbnails">
  <li class="profile-pic">
    <% if @user.image_url.blank?%>
      <% if @user == current_user %>
        <%= link_to image_tag("http://placehold.it/130x130"),\
            edit_user_path(@user.id), :class => "thumbnail" %>
      <% else %>
        <%= image_tag "http://placehold.it/130x130", class: "thumbnail" %>
      <% end %>
    <% else %>
      <% if @user == current_user %>
        <%= link_to image_tag(@user.image_url(:thumb).to_s+
                          "?#{File.mtime(@user.image.file.path).to_i.to_s}"),
                          edit_user_path(@user.id), :class => "thumbnail" %>
      <% else %>
        <%= image_tag @user.image_url(:thumb).to_s, class: "thumbnail" %>
      <% end %>
    <% end %>
  </li>
</ul>
<% if @user.first_name? %>
  <h4> Name: </h4>
  <p>
    <%= @user.first_name+" "+@user.last_name %>
  </p>
<% else %>
  <h4> User email: </h4>
  <p>
    <%= @user.email %>
  </p>
<% end %>
<% if @user.soobooki_id? %>
  <h4> Soobooki ID: </h4>
  <p>
    <%= @user.soobooki_id %>
  </p>
<% end %>
<% if @user.info? %>
  <h4> Info: </h4>
  <p>
    <%= simple_format @user.info %>
  </p>
<% end %>
<% if @controller == "book_posts" %>
  <%= link_to "See Bookshelf", bookshelf(@user), class: "btn" if @action == "show"%>
  <%= link_to "See Movieshelf", movieshelf(@user), class: "btn" %>
<% else %>
  <%= link_to "See Movieshelf", movieshelf(@user), class: "btn" if @action == "show"%>
  <%= link_to "See Bookshelf", bookshelf(@user), class: "btn" %>
<% end %>
<% if @user == current_user and current_user.admin? %>
  <%= link_to "Users Admin Page", users_path, class: "btn" %>
<% end %>

app/views/users/crop_image.html.erb
<div class="row">
  <div class="crop-container span6 offset3">
    <h1>Crop Picture</h1>
    <% filename = @user.image.file.filename %>
    <% if FileTest.exists?(@user.image.file.path.gsub(filename,'large_'+filename)) %>
      <%= image_tag @user.image_url(:large).to_s, id:"cropbox" %>
    <% else %>
      <%= image_tag @user.image_url.to_s, id:"cropbox" %>
    <% end %>
    <%= form_for @user do |f| %>
      <% %w[x y w h].each do |attr| %>
        <%= f.hidden_field "crop_#{attr}" %>
      <% end %>
      <%= f.submit "Crop", class:"btn" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Change Profile</h1>
    <%= render 'form_edit' %>
  </div>
</div>

app/views/users/edit_book_api.js.erb
$('.navbar-search').attr('action','<%= search_books_path(api:@user.book_api) %>')

app/views/users/edit_bookshelf_privacy.js.erb
bookshelf_privacy = <%= @user.bookshelf_privacy %>

app/views/users/edit_movie_api.js.erb
$('.navbar-search').attr('action','<%= search_movies_path(api:@user.movie_api) %>')

app/views/users/edit_movieshelf_privacy.js.erb
movieshelf_privacy = <%= @user.movieshelf_privacy %>

app/views/users/fb_profile_pictures.html.erb
<div class="row">
  <div class="span8 offset2">
    <h1>Facebook Profile Pictures</h1>
    <h3>Select one that you wish to make your Soobooki profile picture</h3>
    <ul class="thumbnails">
      <% @profile_pictures.each do |picture| %>
        <% @user.remote_image_url = picture[:large] %>
        <li>
          <%= form_for @user do |f| %>
            <%= f.hidden_field :remote_image_url %>
            <input src=<%= picture[:thumbnail] %> class="fb-profile-pic" type="image">
          <% end %>            
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="span8 offset2">
    <h1> User Administration Page </h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th>Signup Date</th>
          <th>Confirmed</th>
          <th>Providers</th>
          <th>Login At</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.email, bookshelf_path(user) %></td>
            <td><%= user.created_at.localtime.strftime("%b %-d, %Y") %></td>
            <td><%= user.email_confirmed %></td>
            <td><%= user.authentications.map{|auth| auth.provider}.join(", ") %></td>
            <td>
              <%= format_time(user.latest_login_at) %>
            </td>
            <td>
              <% if current_user.admin? && !user.admin? %>
                <%= link_to 'Delete', user_path(user),
                    :confirm => "Are you sure you want the delete user '#{user.email}'",
                    :method => :delete, :class => "btn" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/need_confirmation.html.erb
<h1> Email Confirmation Needed !</h1>

</br>

<p>
  You have not confirmed your email. </br>
  If you just signed up, an email with a confirmation link has already been sent.</br>
</p>
<p>
  If you are a previous user that never received a confirmation link, click the button below.<br/></br>
  <%= link_to "Request Email", send_confirmation_path, :class => "btn" %>
</p>

app/views/users/new.html.erb
<div class="row">
  <div class="signup-container span6 offset3">
    <h1>Sign Up</h1>
    <%= render 'form_new' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="search-results span7 offset2"></div>
  <div class="my-account-container span7 offset2">
    <h1> My Account Info </h1>
    <div class="account-info">
      <% unless @user.image_url.blank? %>
        <%= image_tag @user.image_url(:thumb).to_s %>
      <% else %>
        <%= image_tag "http://placehold.it/150x150" %>
      <% end %>
      <h3>Email</h3>
      <%= @user.email %>
      <% if @user.first_name? %>
        <p>
          <h3> Name: </h3>
          <%= @user.first_name+" "+@user.last_name %>
        </p>
      <% end %>
      <% if @user.soobooki_id? %>
        <p>
          <h3>Soobooki ID</h3>
          <%= @user.soobooki_id %>
        </p>
      <% end %>
      <% if @user.info? %>
        <p>
          <h3>Info</h3>
          <%= simple_format @user.info %>
        </p>
      <% end %>
    </div>
    <h3>Authentications</h3>
    <table class="table table-striped authentications">
      <tr>
        <th>Provider</th>
        <th>Action</th>
      </tr>
      <% for provider in ["Facebook","Google"] %>
        <tr>
          <td><%= provider %></td>
          <% authentication = @user.authentications.find_by_provider(provider) %>
          <% if authentication %>
            <td><%= link_to "Delete", authentication, :confirm => 
                      "Are you sure you want to delete authentication from #{provider}?",
                    :method => :delete, :class => "btn" %></td>
          <% else %>
            <td><%= link_to "Add", "/auth/facebook", :class => "btn" %></td>
          <% end %>
        </tr>
      <% end %>
    </table>

    <%= link_to 'Edit', edit_user_path(@user), :class => "btn"%>
    <%= link_to 'Delete Account', user_path(@user), 
        :confirm => "Are you sure you want to delete your account?",
        :method => :delete, :class => "btn"%>
    <div class="privacy-settings">
      <h1>Privacy Settings</h1>
      <div class="itemshelf-privacy-container">
        <% ["Bookshelf","Movieshelf"].each do |itemshelf| %>
          <div class="btn-group itemshelf-privacy" data-toggle="buttons-radio">
            <h3><%= itemshelf %></h3>
            <% ["Only Me","Friends","Users","Everyone"].each do |privacy_level| %>
              <% if itemshelf == "Bookshelf" %>
                <% itemshelf_privacy = @user.bookshelf_privacy %>
                <% edit_privacy_path = edit_bookshelf_privacy_path(@user, privacy: privacy_level)%>
              <% else %>
                <% itemshelf_privacy = @user.movieshelf_privacy %>
                <% edit_privacy_path = edit_movieshelf_privacy_path(@user, privacy: privacy_level)%>
              <% end %>
              <% if itemshelf_privacy == privacy_level %>
                <%= link_to privacy_level, edit_privacy_path, class: "btn init-select", remote: true %>
              <% else %>
                <%= link_to privacy_level, edit_privacy_path, class: "btn", remote: true %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <% ["Book","Movie"].each do |item| %>
        <h3><%= item %> Reviews</h3>
        <table class="table table-striped">
          <tr>
            <th><%= item %> Title</th>
            <th class="privacy">Privacy Level</th>
          </tr>
          <% posts = (item == "Book") ? @book_posts : @movie_posts %>
          <% posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td>
                <div class="btn-group" data-toggle="buttons-radio">
                  <% ["Only Me","Friends","Users","Everyone"].each do |privacy_level| %>
                    <% edit_privacy_path = (item == "Book") ?
                       edit_book_post_privacy_path(post, privacy: privacy_level) :
                       edit_movie_post_privacy_path(post, privacy: privacy_level) %>
                    <% if post.privacy == privacy_level %>
                      <%= link_to privacy_level, edit_privacy_path, 
                          class: "btn init-select", remote: true %>
                    <% else %>
                      <%= link_to privacy_level, edit_privacy_path, class: "btn", remote: true %>
                    <% end %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
  </div>
</div>