config/routes.rb
Soobooki::Application.routes.draw do
  Mercury::Engine.routes
  mount Ckeditor::Engine => '/ckeditor'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "email_confirmation/:id" =>"users#email_confirmation", :as => "email_confirmation"
  get "need_confirmation" =>"users#need_confirmation", :as => "need_confirmation"
  get "send_confirmation" =>"users#send_confirmation", :as => "send_confirmation"

  get "edit_search_target/:id" => "users#edit_search_target", :as => "edit_search_target"

  get "bookshelf/:id" => "book_posts#index", :as => "bookshelf"
  get "edit_bookshelf_privacy/:id" => "users#edit_bookshelf_privacy", :as => "edit_bookshelf_privacy"
  get "edit_book_post_privacy/:id" => "book_posts#edit_privacy", :as => "edit_book_post_privacy"
  get "edit_book_api/:id" => "users#edit_book_api", :as => "edit_book_api"

  get "movieshelf/:id" => "movie_posts#index", :as => "movieshelf"
  get "edit_movieshelf_privacy/:id" => "users#edit_movieshelf_privacy", :as => "edit_movieshelf_privacy"
  get "edit_movie_post_privacy/:id" => "movie_posts#edit_privacy", :as => "edit_movie_post_privacy"
  get "edit_movie_api/:id" => "users#edit_movie_api", :as => "edit_movie_api"

  get "user_image_crop/:id" => "users#crop_image", :as => "user_image_crop"
  get "fb_profile_pictures/:id" => "users#fb_profile_pictures", :as => "fb_profile_pictures"

  put "friendships/:id" => "friendships#approve"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  match '/auth/save_access_token' => 'authentications#save_access_token'

  resources :users
  resources :books do
    collection { get :search }
  end
  resources :book_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :movies do
    collection { get :search }
  end
  resources :movie_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :sessions
  resources :password_resets
  resources :friendships
  resources :authentications
  resources :comments
  resources :notifications

  root :to => 'sessions#new'

end

app/models/movie_post.rb
class MoviePost < ActiveRecord::Base
  attr_accessible :day, :month, :movie_id, :review, :title, :user_id, :year,
                  :image, :remote_image_url

  belongs_to :movie
  belongs_to :user

  has_many :comments, order: 'created_at', dependent: :destroy
  has_many :notifications, dependent: :destroy

  mount_uploader :image, ImageUploader

  def title
    if super.present?
      return super
    else
      return movie.title unless movie.nil?
    end
  end

  def image_url(*args)
    if super.present?
      return super
    else
      return movie.image_url(*args) unless movie.nil?
    end
  end
end

app/controllers/movie_posts_controller.rb
class MoviePostsController < ApplicationController
  def index
    if params.has_key?(:id)
      @user = find_user(params[:id])
      redirect_to log_in_path,
      notice: "Couldn't find the user with id: "+params[:id] and return if @user.nil?
    else
      @user = logged_in? # sets @user to current_user
      return if @user.nil?
    end
    if itemshelf_privacy_valid?
      posts_index
    end
  end

  def show
    @movie_post = MoviePost.find(params[:id])
    @user = @movie_post.user
    @movie = Movie.find(@movie_post.movie_id)
    @controller = params[:controller]
    @action = params[:action]

    if post_privacy_valid?
      respond_to do |format|
        format.html # show.html.erb
      end
    end
  end

  def new
    @movie_post = MoviePost.new(year: Time.now.year, month: Time.now.month, day:Time.now.day)
    @controller = params[:controller]

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    if params[:api].present?
      create_from_search and return
    end
    @movie = Movie.new(title: params[:movie_post][:title], image: params[:movie_post][:image],
                remote_image_url: params[:movie_post][:remote_image_url])
    @movie_post = @movie.movie_posts.build(params[:movie_post])
    @movie_post.user = current_user

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie_post, notice: 'Movie post was successfully created.' }
      else
        flash[:notice] = @movie.errors.full_messages[0]
        format.html { render action: "new" }
      end
    end
  end

  def create_from_search
    if params[:api] == "naver"
      image_url = params[:image_url].gsub("mit110","mi")
    elsif params[:api] == "tomato"
      image_url = params[:image_url].gsub("_mob","_ori")
    end

    @movie = Movie.new(title: params[:title], subtitle: params[:subtitle], remote_image_url: image_url,
                   director: params[:director], actor: params[:actor], year: params[:year],
                   rating: params[:rating])
    @movie.movie_posts.build(user_id: current_user.id, year: Time.now.year, month: Time.now.month,
                     day: Time.now.day)
    respond_to do |format|
      if @movie.save!
        format.js
      end
    end
  end

  def edit
    @movie_post = current_user.movie_posts.find(params[:id])
    @movie = Movie.find(@movie_post.movie_id)
    @controller = params[:controller]
  end

  def update
    @movie_post = current_user.movie_posts.find(params[:id])
    params[:movie_post][:review] =
      Sanitize.clean(params[:movie_post][:review],Sanitize::Config::RELAXED)

    respond_to do |format|
      if @movie_post.update_attributes(params[:movie_post])
        format.html { redirect_to @movie_post, notice: 'Movie post was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @movie_post = current_user.movie_posts.find(params[:id])
    @movie_post.destroy

    respond_to do |format|
      format.html { redirect_to movie_posts_url, notice: 'Movie post was successfully deleted.'}
    end
  end

  def mercury_update
    movie_post = current_user.movie_posts.find(params[:id])
    movie_post.review = Sanitize.clean(params[:content][:movie_post_review][:value],
                                Sanitize::Config::RELAXED)
    movie_post.save!
    render text: ""
  end

  def edit_privacy
    @movie_post = MoviePost.find(params[:id])
    @movie_post.privacy = params[:privacy]
    @movie_post.save
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/movie_posts_helper.rb
module MoviePostsHelper
end

app/views/movie_posts/create.js.erb
<% id = @movie.title.gsub(/[[:punct:]\s]/,'')+@movie.year.to_s+
   (@movie.director.present? ? @movie.director.gsub(/[[:punct:]\s]/,'') : '') %>
$('.add_<%= id %>').hide()

app/views/movie_posts/destroy.html.erb
<h1>MoviePosts#destroy</h1>
<p>Find me in app/views/movie_posts/destroy.html.erb</p>

app/views/movie_posts/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Edit Movie</h1>
    <%= render 'items/form', post: @movie_post %>
  </div>
</div>

app/views/movie_posts/edit_privacy.html.erb
<h1>MoviePosts#edit_privacy</h1>
<p>Find me in app/views/movie_posts/edit_privacy.html.erb</p>

app/views/movie_posts/index.html.erb
<div class="row">
  <div class="search-results span7 offset2"></div>
  <div class="movieshelf-container span7 offset2">
    <% if @posts_size == 0 %>
      <% if current_user == @user %>
        <div class="usage-info">
          <h2>Usage Guide</h2>
          <h3>1. Search for a movie</h3>
          <%= image_tag "movie-search-bar.png" %> 
          (click the camera icon for movie search)
          <h3>2. Add it to your movieshelf</h3>
          <%= image_tag "movie.png" %>
          <h3>3. Write reviews and share them with others</h3>
          <%= image_tag "movieshelf.png" %>
        </div>
      <% else %>
        <h3><%= user_name(@user)%> has not added any movies yet. </h3>
      <% end %>
    <% else %>
      <div class="movieshelf">
        <%= render "items/itemshelf"%>
      </div>
      <% unless @next_index >= @posts_size %>
        <%= link_to "See More", movieshelf_path(id: @user.id, next_index: @next_index),
            class: "btn see-more", remote: true %>
      <% end %>
    <% end %>
  </div>
  <div class="span3">
    <%= render 'users/user' %>
  </div>
</div>

app/views/movie_posts/index.js.erb
<% if @last_month_posts %>
   <% @last_month_posts.each do |post| %>
     <% item = find_movie(post.movie_id) %>
     <% if item %>
       $(".movieshelf ul.<%=post.year%>_<%=post.month%>").append("<%= j render "items/item_thumbnail", :item => item, :post => post %>")
     <% end %>
   <% end %>
<% end %>
$(".movieshelf").append("<%= j render "items/itemshelf" %>")
$("a.see-more").attr("href", "<%= j movieshelf_path(id: @user.id, next_index: @next_index) %>")
<% if @next_index >= @posts_size %>
   $("a.see-more").hide()
<% end %>

app/views/movie_posts/mercury_update.html.erb
<h1>MoviePosts#mercury_update</h1>
<p>Find me in app/views/movie_posts/mercury_update.html.erb</p>

app/views/movie_posts/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Add Movie</h1>
    <%= render 'items/form', post: @movie_post %>
  </div>
</div>

app/views/movie_posts/show.html.erb
<%= javascript_include_tag "mercury_override" %>
<div class="row">
  <div class="search-results span6 offset2"></div>
  <div class="movie-post-container span6 offset2">
    <% if @movie_post.title.present? %>
      <h1><%= @movie_post.title %></h1>
    <% else %>    
      <h1><%= @movie.title %></h1>
    <% end %>
    <% if @movie_post.image_url.present? %>
      <%= image_tag @movie_post.image_url(:default).to_s %>        
    <% elsif @movie.image_url.present? %>
      <%= image_tag @movie.image_url(:default).to_s %>        
    <% end %>
    <% if @movie_post.year != 0 %>
      <h4> Date Watched </h4>
      <%= format_date(@movie_post.year,@movie_post.month,@movie_post.day) %>
    <% end %>
    <p>
      <div id="movie_post_review" class="mercury-region" data-type="editable">
        <%= raw @movie_post.review %>
      </div>
    </p>
    <%= render "comments/comment_list", post: @movie_post %>
    <% if current_user.present? %>
      <%= render "comments/new_comment", post: @movie_post %>
    <% end %>
    <% if current_user == @user %>
      <%= link_to 'Edit Post', edit_movie_post_path(@movie_post), :class => "btn", id: "ck_edit_link" %>
      <%= link_to 'Mercury Editor', "/editor"+request.path, class: "btn", id: "mercury_edit_link", data: {save_url: mercury_update_movie_post_path(@movie_post)} %>
      <%= link_to 'Delete', movie_post_path(@movie_post), 
          :confirm => "Are you sure you want to delete '#{@movie.title}'?",
          :method => :delete, :class => "btn", id: "delete_link"%>
    <% end %>
  </div>
  <div class="span3 offset1">
    <%= render 'users/user' %>
  </div>
</div>

app/views/movie_posts/update.html.erb
<h1>MoviePosts#update</h1>
<p>Find me in app/views/movie_posts/update.html.erb</p>