config/routes.rb
Soobooki::Application.routes.draw do
  Mercury::Engine.routes
  mount Ckeditor::Engine => '/ckeditor'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get "email_confirmation/:id" =>"users#email_confirmation", :as => "email_confirmation"
  get "need_confirmation" =>"users#need_confirmation", :as => "need_confirmation"
  get "send_confirmation" =>"users#send_confirmation", :as => "send_confirmation"

  get "edit_search_target/:id" => "users#edit_search_target", :as => "edit_search_target"

  get "bookshelf/:id" => "book_posts#index", :as => "bookshelf"
  get "edit_bookshelf_privacy/:id" => "users#edit_bookshelf_privacy", :as => "edit_bookshelf_privacy"
  get "edit_book_post_privacy/:id" => "book_posts#edit_privacy", :as => "edit_book_post_privacy"
  get "edit_book_api/:id" => "users#edit_book_api", :as => "edit_book_api"

  get "movieshelf/:id" => "movie_posts#index", :as => "movieshelf"
  get "edit_movieshelf_privacy/:id" => "users#edit_movieshelf_privacy", :as => "edit_movieshelf_privacy"
  get "edit_movie_post_privacy/:id" => "movie_posts#edit_privacy", :as => "edit_movie_post_privacy"
  get "edit_movie_api/:id" => "users#edit_movie_api", :as => "edit_movie_api"

  get "user_image_crop/:id" => "users#crop_image", :as => "user_image_crop"
  get "fb_profile_pictures/:id" => "users#fb_profile_pictures", :as => "fb_profile_pictures"

  put "friendships/:id" => "friendships#approve"

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'
  match '/auth/save_access_token' => 'authentications#save_access_token'

  resources :users
  resources :books do
    collection { get :search }
  end
  resources :book_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :movies do
    collection { get :search }
  end
  resources :movie_posts do
    member { post :mercury_update }
    resources :comments
  end
  resources :sessions
  resources :password_resets
  resources :friendships
  resources :authentications
  resources :comments
  resources :notifications

  root :to => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soobooki</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top" id="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="<%= bookshelf(current_user) %>">Soobooki</a>
          <ul class="nav" id="top-nav">
            <li><%= link_to 'Books', bookshelf(current_user) %></li>
            <li><%= link_to 'Movies', movieshelf(current_user) %></li>
            <li><%= link_to 'Friends', friendships_path %></li>
            <% id = current_user ? current_user : 0 %>
            <li><%= link_to 'Notifications', notifications_path(id: id) %></li>
            <li><%= link_to 'My Account', user_path(id: id) %></li>
            <% if current_user %>
              <li><%= link_to 'Log out', log_out_path %></li>
            <% else %>
              <li><%= link_to 'Log in ', log_in_path %></li>
            <% end %>
            <li>
              <% if current_user.nil? %>
                <% api = "daum" %>
                <% search_path = search_books_path(api: api) %>
                <% placeholder = "Book Title" %>
              <% elsif current_user.search_target == "books" %>
                <% api = current_user.book_api %>
                <% search_path = search_books_path(api: api) %>
                <% placeholder = "Book Title" %>
              <% else %>
                <% api = current_user.movie_api %>
                <% search_path = search_movies_path(api: api) %>
                <% placeholder = "Movie Title" %>
              <% end %>

              <%= form_tag search_path, method: "get", remote: true, class: "navbar-search" do %>
                <%= text_field_tag "query", nil, placeholder: placeholder,
                    class: "input-medium search-query" %>
                <i class="icon-search"></i>
                <% if current_user.present? %>
                  <a data-remote="true" title="book search"
                     href="<%= edit_search_target_path(current_user,search_target:"books") %>">
                    <i class="icon-book icon-white"></i>
                  </a>
                  <a data-remote="true" title="movie search"
                     href="<%= edit_search_target_path(current_user,search_target:"movies") %>">
                    <i class="icon-facetime-video icon-white"></i>
                  </a>
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="span6 offset2">
          <% flash.each do |name,msg| %>
            <div class="alert">
              <button class="close" data-dismiss="alert">×</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury', 'mercury_overrides' %>
  </head>
  <body>
    <script type="text/javascript">
      var saveUrl = null; // Set to the url that you want to save any given page to.
      var options = {
        saveStyle: 'form',  // 'form', or 'json' (default json)
        saveMethod: null, // 'POST', or 'PUT', (create, vs. update -- default POST)
        visible: null     // if the interface should start visible or not (default true)
      };

      <!-- Mix in any configurations provided through Rails.application.config.mercury_config -->
      <% if Rails.application.config.respond_to?(:mercury_config) %>
        jQuery.extend(Mercury.config, <%= Rails.application.config.mercury_config.to_json.html_safe %>);
      <% end -%>

      <!-- Mix in any options for PageEditor provided through Rails.application.config.mercury_page_editor_config -->
      <% if Rails.application.config.respond_to?(:mercury_page_editor_config) %>
        jQuery.extend(options, <%= Rails.application.config.mercury_page_editor_config.to_json.html_safe %>);
      <% end -%>

      <!-- Instantiate the PageEditor -->
      new Mercury.PageEditor(saveUrl, options);
    </script>
  </body>
</html>